### ISSUE TITLE
Not working on Wayland

### ISSUE THREAD

**Issue by l0drex** [flathub/de.bund.ausweisapp.ausweisapp2#25]
Tried to use it on Wayland, but I just got funny cursor animations. Removing the access to the `socket=wayland` in flatseal fixed that.

I am using arch with KDE Plasma 5.27.4

<details>
<summary>Detailed system specs</summary>

```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.13-zen-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i5-10400F CPU @ 2.90GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
Product Name: H570 Phantom Gaming 4
```

</details>

**Comment by ecsgh** [comment]
Version 2.0.0 native as an app, i.e. not flatpack, also does not work directly under plasma wayland.
It does work under plasma X11.
There is practically no display. The content of the window only flickers.

**Comment by l0drex** [comment]
I just tried to open it on Fedora 39 with Gnome on Wayland, and it works fine. So either there was an update somewhere, or it is plasma / kwin specific. I will test again later on my KDE machine

**Comment by der-eismann** [comment]
Were you able to test it again @l0drex ?

**Comment by misery** [comment]
There is no special X11 handling in the AusweisApp. Those problems should be a Qt bug.

**Comment by ecsgh** [comment]
> There is no special X11 handling in the AusweisApp. Those problems should be a Qt bug.

Think not.

It will not run under Nvidia, plasma and Wayland.
It will run under Nvidia, plasma, x11.

Perhaps it is an Nvidia error.

**Comment by l0drex** [comment]
> Were you able to test it again @l0drex ?

Just tested it, works like a charm. Seems to be fixed :+1: 
I should add that I switched from a Gtx 1060 to a Rtx 2080 in the meantime, don't know if that is relevant (probably not).

<details>
<summary>Sytem and app versions</summary>

de.bund.ausweisapp.ausweisapp2 app version: 2.0.1
Flatpak: 1.15.6

Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.6.9-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i5-10400F CPU @ 2.90GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2080/PCIe/SSE2
</details>

**Comment by ecsgh** [comment]
It is not fixed!

It does not work under Wayland. 

The window flickers.
Nothing is legible.

Not with own build in obs suse.
Not with package from flathub.

System is:
Operating System: openSUSE Leap 15.5
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 5.14.21-150500.55.39-default (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 1600 Six-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

With X11 it will run!

**Comment by l0drex** [comment]
What version of the NVIDIA driver do you use? I have 545.29.06 on my system (use `nvidia-smi` to get that info)

**Comment by ecsgh** [comment]
The same:
sudo zypper se -si nvidia: 545.29.06-lp155.18.1
This is package from suse. Which is from nvidia.

**Comment by der-eismann** [comment]
> It does not work under Wayland.
> The window flickers. Nothing is legible.
> Not with own build in obs suse. Not with package from flathub.

Sounds like an issue with your system or the application itself then, not this flatpak version. Maybe you should contact the developer then.

**Comment by ecsgh** [comment]
Isn't this the official flathub package?
Under discover in KDE appears:
"Official authentication app; Covernikus GmbH"

The whole thing regarding this application is very dubious.
Since this is an application of the federal government, there shouldn't be any other places there. Or am I seeing this a bit wrong?
Issius cannot be specified on the official github.
And nothing is really tracked transparently.
It's a typical federal app. Taxpayers' money is being squandered and there's talk of open source. The code is open. But that's it. :-(
I had already tried that directly. But there is absolutely no way to really do anything or help. As long as the tax money keeps flowing...

Is this official or not?

**Comment by misery** [comment]
This flatpak is NOT official! Also there is no linux support.

The AusweisApp has no special handling of X11 or Wayland. If there is any problem, it is a driver, system, flatpak or Qt issue. Maybe you should create a bug report to Qt.

**Comment by der-eismann** [comment]
The wording is a bit confusing maybe. The AusweisApp as provided at https://github.com/Governikus/AusweisApp is the official application for the German ID cards. The distribution via Flatpak is a community-based effort to make it accessible for a broader audience. You can also see [here](https://www.ausweisapp.bund.de/open-source-software):
> Bitte beachten Sie, dass für die folgenden App-Varianten leider kein Support angeboten werden kann.

I'm pretty happy with where my tax money went with this. We have an open source version that runs on almost any platform. There might be some few edge cases, but I can live with that.

**Comment by misery** [comment]
Yeah, your are right. Thanks for clarify. :-)

Maybe you did not notice but I'm a developer of the AusweisApp and have rights for this repository. But there is no official support of Governikus/BSI/BMI. It's just because I'm an open source enthusiast, too.

**Comment by ecsgh** [comment]
@the-ice-man
I am not at all satisfied with what happens to my tax money. And if it's not running under wayland, that's quite a few.

@misery
Their answer is also very dubious. 
They say they are developers and have access to the G******** repo. 
At the same time they say there is no official support.
So what now?
You can only write an email to this company. Nothing more.
The message is then simply dismissed. You can't read about the reported errors and solutions anywhere.

**Comment by der-eismann** [comment]
It's running perfectly fine under Wayland for me, the original creator of this issue and probably others as well. It doesn't work on _your_ machine. You can also call them at the number mentioned on [their website](https://www.ausweisapp.bund.de/home/), but they will also tell you they can't help with your edge case. You can't expect them to provide support for dozens of distributions with tons of different hardware.

And he can work at Governikus and use his free time to work on the Flatpak distribution, I don't see where this is a problem. He is not obliged to use his free time to provide support.

**Comment by ecsgh** [comment]
Who is talking about dozens of distributions?
OpenSUSE is probably not a small one. At least not in Germany. Digitization will never work that way. But when even such excuses are made....

The problem is that the company claims the software is open source. It collects taxpayers' money for it. But it's not really open source. That's the problem.

But let's leave it here. It doesn't fit here and I'm just getting upset again.

**Comment by glaubitz** [comment]
> Who is talking about dozens of distributions? OpenSUSE is probably not a small one. At least not in Germany. Digitization will never work that way. But when even such excuses are made....

For what is worth, I am the maintainer of the AusweisApp package in openSUSE. I encourage you to use the AusweisApp package provided by openSUSE instead of the Flatpak package.

> The problem is that the company claims the software is open source. It collects taxpayers' money for it. But it's not really open source. That's the problem.

No, the problem is that the German government **does not pay for Linux support**. What you are getting is the result of @misery providing you with Linux support in his free time. He is not receiving a single Cent of tax payer money for that.

So, he actually gets to decide himself how much time he spends on improving Linux support and if he doesn't feel like supporting a particular software configuration, that's completely up to him.

> But let's leave it here. It doesn't fit here and I'm just getting upset again.

Well, as @misery tried to explain many times, there is nothing specific in AusweisApp that is relevant to X11 or Wayland. AusweisApp builds against Qt and it uses the API available in Qt. AusweisApp doesn't even know whether it's running on X11 or Wayland or even whatever operating system you use. It uses a set of libraries, most importantly Qt, to talk to the operating system.

So, if it's showing weird display artifacts, it's extremely like **not** a problem with AusweisApp but with the rest of the environment. It's either a bug in Qt or in your graphics driver. To provide an analog example: If your newly purchased television shows a boring talk shows all day long, it's not a problem with the TV itself but your broadcaster. The TV behaves within spec.

Also, it works perfectly fine for me on openSUSE Tumbleweed on Wayland. If it doesn't work on your openSUSE setup, you need to be more specific about the problem and help the developers, who again do all of this stuff for Linux in their free time, debug and fix the issue.

Please understand that free software doesn't mean that people work for free.

To quote a famous saying: Free software means as free as in free speech, but not as in in free beer.
