### ISSUE TITLE
Driver is not recognized

### ISSUE THREAD

**Issue by Tealk** [flathub/de.bund.ausweisapp.ausweisapp2#6]
According to support, the device does not require its own driver, but I still get the following message:
![grafik](https://user-images.githubusercontent.com/12276250/142385582-00c8a0bf-933b-4d71-9611-00db1203df99.png)

**Comment by e-user** [comment]
@Tealk would you mind trying to run AusweisApp without Flatpak in order to eliminate possible sources of error? I can't really help as I don't have the device in question. Could you also please provide more information on distribution and kernel in use?

**Comment by Tealk** [comment]
I use Manjaro with Kernel 5.15.2

**Comment by misery** [comment]
Could you try to install ```ccid``` package locally? The Flatpak does not add drivers by itself - it just connects to your local pcsc-lite daemon.

**Comment by Tealk** [comment]
community/ccid 1.4.36-1 [installed]

I also had the "Ausweisapp2" created via AUR, I have the same problem there too.

**Comment by e-user** [comment]
In that case, there is unfortunately nothing we could do with the Flatpak version of AusweisApp2 in order to solve this problem, as it appears to be either a lack of kernel drivers, or missing support in your version of `ccid`. Have you tried reaching out to https://github.com/LudovicRousseau/CCID and/or https://www.ausweisapp.bund.de/hilfe-und-support/support-fehlermeldungen/?
